// Mock resume generator that creates a simple PDF-like document
export function generateResumePDF(data: {
  file?: File;
  fileText?: string;
  urls: string[];
  missingSections?: string;
}): Blob {
  // Create a simple text-based resume content
  const resumeContent = `
═══════════════════════════════════════════════════════
                    PROFESSIONAL RESUME
═══════════════════════════════════════════════════════

Generated on: ${new Date().toLocaleDateString()}

CONTACT INFORMATION
---------------------------------------------------
${data.urls.length > 0 ? data.urls.map((url, i) => `${i + 1}. ${url}`).join('\n') : 'No URLs provided'}

RESUME DETAILS
---------------------------------------------------
${data.fileText || 'Resume file uploaded: ' + (data.file?.name || 'resume.pdf')}

${data.missingSections ? `\nADDITIONAL SECTIONS
---------------------------------------------------
${data.missingSections}` : ''}

---------------------------------------------------
This resume was generated by Resume Assistant AI
═══════════════════════════════════════════════════════
  `.trim();

  // Create a blob with the content
  const blob = new Blob([resumeContent], { type: 'application/pdf' });
  return blob;
}
